# Generated by Django 5.1.7 on 2025-05-12 20:18

import apps.waste.models.waste_model
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('environmental_license', models.CharField(blank=True, max_length=100, null=True)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Waste Manager',
                'verbose_name_plural': 'Waste Managers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('departure_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(choices=[('KG', 'Kilograms'), ('TON', 'Tons'), ('M3', 'Cubic meters'), ('L', 'Liters'), ('UN', 'Units')], default='KG', max_length=5)),
                ('treatment_method', models.CharField(choices=[('RECYCLING', 'Recycling'), ('COMPOSTING', 'Composting'), ('INCINERATION', 'Incineration'), ('LANDFILL', 'Landfill'), ('SECURITY_CELL', 'Security Cell'), ('ENCAPSULATION', 'Encapsulation'), ('SPECIAL_TREATMENT', 'Special Treatment'), ('REUSE', 'Reuse/Reconditioning'), ('OTHER', 'Other (Specify)')], max_length=20)),
                ('other_method', models.CharField(blank=True, max_length=100, null=True)),
                ('manifest_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('TREATED', 'Treated'), ('CERTIFIED', 'Certificate Issued'), ('RETURNED', 'Returned/Rejected')], default='SCHEDULED', max_length=20)),
                ('carrier', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.companyarea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastemanager')),
            ],
            options={
                'verbose_name': 'Waste Destination',
                'verbose_name_plural': 'Waste Destinations',
                'ordering': ['-departure_date', 'waste_type'],
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(choices=[('KG', 'Kilograms'), ('TON', 'Tons'), ('M3', 'Cubic meters'), ('L', 'Liters'), ('UN', 'Units')], default='KG', max_length=5)),
                ('container_type', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.companyarea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Waste Record',
                'verbose_name_plural': 'Waste Records',
                'ordering': ['-record_date', 'area', 'waste_type'],
            },
        ),
        migrations.CreateModel(
            name='WasteMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('file', models.FileField(upload_to=apps.waste.models.waste_model.get_waste_media_path)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(max_length=50)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='waste.wastedestination')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='waste.wasterecord')),
            ],
            options={
                'verbose_name': 'Waste File',
                'verbose_name_plural': 'Waste Files',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('ORDINARY', 'Ordinary'), ('RECYCLABLE', 'Recyclable'), ('HAZARDOUS', 'Hazardous'), ('SPECIAL', 'Special'), ('BIODEGRADABLE', 'Biodegradable'), ('ELECTRONIC', 'Electronic Waste')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('identification_color', models.CharField(blank=True, max_length=20, null=True)),
                ('requires_special_treatment', models.BooleanField(default=False)),
                ('handling_instructions', models.TextField(blank=True, null=True)),
                ('storage_requirements', models.TextField(blank=True, null=True)),
                ('safety_measures', models.TextField(blank=True, null=True)),
                ('legal_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Waste Type',
                'verbose_name_plural': 'Waste Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastetype'),
        ),
        migrations.CreateModel(
            name='WasteIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=200)),
                ('indicator_type', models.CharField(choices=[('GENERATION', 'Waste Generation'), ('RECYCLING', 'Recycling Rate'), ('REDUCTION', 'Waste Reduction'), ('HAZARDOUS', 'Hazardous Waste Management'), ('COST', 'Waste Management Cost')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('formula', models.TextField(blank=True, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('measurement_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('baseline_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('waste_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.wastetype')),
            ],
            options={
                'verbose_name': 'Waste Indicator',
                'verbose_name_plural': 'Waste Indicators',
                'ordering': ['indicator_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='wastedestination',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastetype'),
        ),
    ]
