# Generated by Django 5.1.7 on 2025-05-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchyitem',
            name='custom_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Custom CSS Class'),
        ),
        migrations.AddField(
            model_name='hierarchyitem',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='hierarchyitem',
            name='is_draggable',
            field=models.BooleanField(default=True, verbose_name='Is Draggable'),
        ),
        migrations.AddField(
            model_name='hierarchyitem',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name='Is Editable'),
        ),
    ]
